-- SMPPlatform PostgreSQL baseline migration (V001).
-- This migration intentionally creates only smp_-prefixed objects. It does not alter,
-- reference, or assume the names of any existing Kairu shared tables.
-- UUID values are generated by SMPPlatform application code; no database extension is required.
-- Apply with a dedicated migration role and an established migration runner.

BEGIN;

CREATE TABLE smp_worlds (
  world_id text PRIMARY KEY CHECK (world_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  minecraft_world_name text NOT NULL UNIQUE,
  display_name text NOT NULL,
  public_type text NOT NULL,
  module_type text NOT NULL,
  season_label text NOT NULL,
  status text NOT NULL CHECK (status IN ('LIVE','SEASONAL','ARCHIVED','MAINTENANCE','OFFLINE')),
  description text NOT NULL,
  size_label text NOT NULL,
  difficulty_label text NOT NULL,
  border_size integer NOT NULL CHECK (border_size >= 0),
  pvp_mode text NOT NULL,
  guild_mode text NOT NULL,
  points_enabled boolean NOT NULL DEFAULT false,
  currency_id text,
  claims_enabled boolean NOT NULL DEFAULT false,
  economy_enabled boolean NOT NULL DEFAULT false,
  inventory_group text NOT NULL,
  reset_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  archive_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  discord_enabled boolean NOT NULL DEFAULT false,
  website_visible boolean NOT NULL DEFAULT true,
  map_visible boolean NOT NULL DEFAULT true,
  maintenance_mode boolean NOT NULL DEFAULT false,
  access_permission text NOT NULL,
  spawn_x double precision NOT NULL,
  spawn_y double precision NOT NULL,
  spawn_z double precision NOT NULL,
  spawn_yaw real NOT NULL DEFAULT 0,
  spawn_pitch real NOT NULL DEFAULT 0,
  registry_revision bigint NOT NULL DEFAULT 0 CHECK (registry_revision >= 0),
  config_origin text NOT NULL DEFAULT 'LOCAL_BOOTSTRAP',
  last_synced_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((points_enabled AND currency_id IS NOT NULL) OR NOT points_enabled)
);

CREATE TABLE smp_world_seasons (
  world_season_id uuid PRIMARY KEY,
  world_id text NOT NULL REFERENCES smp_worlds(world_id) ON DELETE RESTRICT,
  season_key text NOT NULL,
  display_name text NOT NULL,
  state text NOT NULL CHECK (state IN ('PLANNED','ACTIVE','ENDED','ARCHIVED')),
  starts_at timestamptz,
  ends_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (world_id, season_key),
  CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at)
);
CREATE INDEX smp_world_seasons_world_idx ON smp_world_seasons(world_id, state);

-- platform_user_id is an external Central Platform/Kairu reference, intentionally not a foreign key.
CREATE TABLE smp_players (
  player_id uuid PRIMARY KEY,
  platform_user_id uuid UNIQUE,
  display_name text,
  first_join_at timestamptz,
  last_join_at timestamptz,
  last_seen_at timestamptz,
  total_playtime_seconds bigint NOT NULL DEFAULT 0 CHECK (total_playtime_seconds >= 0),
  current_world_id text REFERENCES smp_worlds(world_id) ON DELETE SET NULL,
  membership_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  moderation_status text NOT NULL DEFAULT 'ACTIVE',
  website_linked boolean NOT NULL DEFAULT false,
  discord_linked boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX smp_players_current_world_idx ON smp_players(current_world_id) WHERE current_world_id IS NOT NULL;

CREATE TABLE smp_minecraft_accounts (
  account_id uuid PRIMARY KEY,
  player_id uuid NOT NULL REFERENCES smp_players(player_id) ON DELETE CASCADE,
  minecraft_uuid uuid NOT NULL UNIQUE,
  current_username text NOT NULL,
  username_normalized text NOT NULL,
  edition text NOT NULL CHECK (edition IN ('JAVA','BEDROCK')),
  floodgate_xuid text,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  is_primary boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (edition, floodgate_xuid),
  CHECK ((edition = 'BEDROCK' AND floodgate_xuid IS NOT NULL) OR edition = 'JAVA')
);
CREATE UNIQUE INDEX smp_minecraft_accounts_one_primary_per_player
  ON smp_minecraft_accounts(player_id) WHERE is_primary;
CREATE INDEX smp_minecraft_accounts_player_idx ON smp_minecraft_accounts(player_id);
CREATE INDEX smp_minecraft_accounts_username_idx ON smp_minecraft_accounts(username_normalized);

CREATE TABLE smp_player_world_stats (
  player_world_stats_id uuid PRIMARY KEY,
  account_id uuid NOT NULL REFERENCES smp_minecraft_accounts(account_id) ON DELETE CASCADE,
  world_id text NOT NULL REFERENCES smp_worlds(world_id) ON DELETE RESTRICT,
  world_season_id uuid REFERENCES smp_world_seasons(world_season_id) ON DELETE SET NULL,
  playtime_seconds bigint NOT NULL DEFAULT 0 CHECK (playtime_seconds >= 0),
  blocks_placed bigint NOT NULL DEFAULT 0 CHECK (blocks_placed >= 0),
  blocks_mined bigint NOT NULL DEFAULT 0 CHECK (blocks_mined >= 0),
  mob_kills bigint NOT NULL DEFAULT 0 CHECK (mob_kills >= 0),
  player_kills bigint NOT NULL DEFAULT 0 CHECK (player_kills >= 0),
  deaths bigint NOT NULL DEFAULT 0 CHECK (deaths >= 0),
  distance_metres numeric(20,2) NOT NULL DEFAULT 0 CHECK (distance_metres >= 0),
  achievements jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX smp_player_world_stats_scope_uq
  ON smp_player_world_stats(account_id, world_id, COALESCE(world_season_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE INDEX smp_player_world_stats_world_idx ON smp_player_world_stats(world_id, updated_at DESC);

CREATE TABLE smp_guilds (
  guild_id uuid PRIMARY KEY,
  name text NOT NULL,
  name_normalized text NOT NULL UNIQUE,
  tag text NOT NULL,
  tag_normalized text NOT NULL UNIQUE,
  description text NOT NULL DEFAULT '',
  owner_account_id uuid NOT NULL REFERENCES smp_minecraft_accounts(account_id) ON DELETE RESTRICT,
  home_world_id text REFERENCES smp_worlds(world_id) ON DELETE SET NULL,
  home_x double precision,
  home_y double precision,
  home_z double precision,
  home_yaw real,
  home_pitch real,
  website_visible boolean NOT NULL DEFAULT true,
  discord_reference text,
  level integer NOT NULL DEFAULT 1 CHECK (level >= 1),
  state text NOT NULL DEFAULT 'ACTIVE' CHECK (state IN ('ACTIVE','DISBANDED','LOCKED')),
  created_at timestamptz NOT NULL DEFAULT now(),
  disbanded_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CHECK ((home_world_id IS NULL) = (home_x IS NULL)),
  CHECK (disbanded_at IS NULL OR state = 'DISBANDED')
);

CREATE TABLE smp_guild_ranks (
  guild_rank_id uuid PRIMARY KEY,
  guild_id uuid NOT NULL REFERENCES smp_guilds(guild_id) ON DELETE CASCADE,
  rank_key text NOT NULL,
  display_name text NOT NULL,
  priority integer NOT NULL CHECK (priority >= 0),
  permissions jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_default boolean NOT NULL DEFAULT false,
  is_owner_rank boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (guild_id, rank_key),
  UNIQUE (guild_id, priority)
);
CREATE UNIQUE INDEX smp_guild_ranks_one_default_idx ON smp_guild_ranks(guild_id) WHERE is_default;
CREATE UNIQUE INDEX smp_guild_ranks_one_owner_idx ON smp_guild_ranks(guild_id) WHERE is_owner_rank;

CREATE TABLE smp_guild_members (
  guild_member_id uuid PRIMARY KEY,
  guild_id uuid NOT NULL REFERENCES smp_guilds(guild_id) ON DELETE CASCADE,
  account_id uuid NOT NULL REFERENCES smp_minecraft_accounts(account_id) ON DELETE RESTRICT,
  guild_rank_id uuid NOT NULL REFERENCES smp_guild_ranks(guild_rank_id) ON DELETE RESTRICT,
  joined_at timestamptz NOT NULL DEFAULT now(),
  left_at timestamptz,
  leave_reason text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CHECK (left_at IS NULL OR left_at >= joined_at)
);
CREATE UNIQUE INDEX smp_guild_members_one_active_guild_idx ON smp_guild_members(account_id) WHERE left_at IS NULL;
CREATE INDEX smp_guild_members_guild_active_idx ON smp_guild_members(guild_id) WHERE left_at IS NULL;

CREATE TABLE smp_guild_invites (
  guild_invite_id uuid PRIMARY KEY,
  guild_id uuid NOT NULL REFERENCES smp_guilds(guild_id) ON DELETE CASCADE,
  invitee_account_id uuid NOT NULL REFERENCES smp_minecraft_accounts(account_id) ON DELETE CASCADE,
  inviter_account_id uuid NOT NULL REFERENCES smp_minecraft_accounts(account_id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','ACCEPTED','DECLINED','REVOKED','EXPIRED')),
  expires_at timestamptz NOT NULL,
  responded_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (expires_at > created_at),
  CHECK (responded_at IS NULL OR responded_at >= created_at)
);
CREATE UNIQUE INDEX smp_guild_invites_pending_uq ON smp_guild_invites(guild_id, invitee_account_id) WHERE status = 'PENDING';
CREATE INDEX smp_guild_invites_invitee_idx ON smp_guild_invites(invitee_account_id, status, expires_at);

CREATE TABLE smp_guild_stats (
  guild_stats_id uuid PRIMARY KEY,
  guild_id uuid NOT NULL REFERENCES smp_guilds(guild_id) ON DELETE CASCADE,
  world_id text REFERENCES smp_worlds(world_id) ON DELETE SET NULL,
  world_season_id uuid REFERENCES smp_world_seasons(world_season_id) ON DELETE SET NULL,
  metric_key text NOT NULL,
  metric_value numeric(24,6) NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX smp_guild_stats_scope_uq
  ON smp_guild_stats(guild_id, COALESCE(world_id, ''), COALESCE(world_season_id, '00000000-0000-0000-0000-000000000000'::uuid), metric_key);

CREATE TABLE smp_point_accounts (
  point_account_id uuid PRIMARY KEY,
  currency_id text NOT NULL,
  owner_kind text NOT NULL CHECK (owner_kind IN ('PLAYER','GUILD')),
  player_id uuid REFERENCES smp_players(player_id) ON DELETE CASCADE,
  guild_id uuid REFERENCES smp_guilds(guild_id) ON DELETE CASCADE,
  balance numeric(20,6) NOT NULL DEFAULT 0,
  version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((owner_kind = 'PLAYER' AND player_id IS NOT NULL AND guild_id IS NULL)
      OR (owner_kind = 'GUILD' AND guild_id IS NOT NULL AND player_id IS NULL))
);
CREATE UNIQUE INDEX smp_point_accounts_player_currency_uq ON smp_point_accounts(player_id, currency_id) WHERE player_id IS NOT NULL;
CREATE UNIQUE INDEX smp_point_accounts_guild_currency_uq ON smp_point_accounts(guild_id, currency_id) WHERE guild_id IS NOT NULL;

CREATE TABLE smp_point_transactions (
  point_transaction_id uuid PRIMARY KEY,
  point_account_id uuid NOT NULL REFERENCES smp_point_accounts(point_account_id) ON DELETE RESTRICT,
  currency_id text NOT NULL,
  amount numeric(20,6) NOT NULL CHECK (amount <> 0),
  balance_before numeric(20,6) NOT NULL,
  balance_after numeric(20,6) NOT NULL,
  source text NOT NULL CHECK (source IN ('GAMEPLAY','ADMIN','ACHIEVEMENT','EVENT','GUILD','QUEST','SKRIPT','API','SYSTEM','REFUND','ADJUSTMENT')),
  reason text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  world_id text REFERENCES smp_worlds(world_id) ON DELETE SET NULL,
  actor_account_id uuid REFERENCES smp_minecraft_accounts(account_id) ON DELETE SET NULL,
  idempotency_key text NOT NULL UNIQUE,
  correlation_id uuid,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  CHECK (balance_after = balance_before + amount)
);
CREATE INDEX smp_point_transactions_account_time_idx ON smp_point_transactions(point_account_id, occurred_at DESC);
CREATE INDEX smp_point_transactions_world_time_idx ON smp_point_transactions(world_id, occurred_at DESC);
CREATE INDEX smp_point_transactions_correlation_idx ON smp_point_transactions(correlation_id) WHERE correlation_id IS NOT NULL;

CREATE TABLE smp_hardcore_seasons (
  hardcore_season_id uuid PRIMARY KEY,
  world_id text NOT NULL REFERENCES smp_worlds(world_id) ON DELETE RESTRICT,
  season_key text NOT NULL,
  state text NOT NULL CHECK (state IN ('PLANNED','ACTIVE','RESET_WINDOW','ENDED','ARCHIVED')),
  reset_timezone text NOT NULL,
  reset_day text NOT NULL,
  reset_time time NOT NULL,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (world_id, season_key),
  CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at)
);

CREATE TABLE smp_hardcore_players (
  hardcore_player_id uuid PRIMARY KEY,
  hardcore_season_id uuid NOT NULL REFERENCES smp_hardcore_seasons(hardcore_season_id) ON DELETE CASCADE,
  account_id uuid NOT NULL REFERENCES smp_minecraft_accounts(account_id) ON DELETE CASCADE,
  status text NOT NULL CHECK (status IN ('ALIVE','DEAD','SPECTATING','RESET_ELIGIBLE','LOCKED')),
  survival_time_seconds bigint NOT NULL DEFAULT 0 CHECK (survival_time_seconds >= 0),
  days_survived integer NOT NULL DEFAULT 0 CHECK (days_survived >= 0),
  deaths integer NOT NULL DEFAULT 0 CHECK (deaths >= 0),
  mob_kills bigint NOT NULL DEFAULT 0 CHECK (mob_kills >= 0),
  player_kills bigint NOT NULL DEFAULT 0 CHECK (player_kills >= 0),
  boss_kills bigint NOT NULL DEFAULT 0 CHECK (boss_kills >= 0),
  distance_metres numeric(20,2) NOT NULL DEFAULT 0 CHECK (distance_metres >= 0),
  blocks_mined bigint NOT NULL DEFAULT 0 CHECK (blocks_mined >= 0),
  hardcore_points numeric(20,6) NOT NULL DEFAULT 0,
  best_survival_seconds bigint NOT NULL DEFAULT 0 CHECK (best_survival_seconds >= 0),
  status_changed_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (hardcore_season_id, account_id)
);
CREATE INDEX smp_hardcore_players_leaderboard_idx ON smp_hardcore_players(hardcore_season_id, survival_time_seconds DESC);
CREATE INDEX smp_hardcore_players_status_idx ON smp_hardcore_players(hardcore_season_id, status);

CREATE TABLE smp_hardcore_deaths (
  hardcore_death_id uuid PRIMARY KEY,
  hardcore_player_id uuid NOT NULL REFERENCES smp_hardcore_players(hardcore_player_id) ON DELETE CASCADE,
  world_id text NOT NULL REFERENCES smp_worlds(world_id) ON DELETE RESTRICT,
  death_cause text NOT NULL,
  killer_account_id uuid REFERENCES smp_minecraft_accounts(account_id) ON DELETE SET NULL,
  x double precision NOT NULL,
  y double precision NOT NULL,
  z double precision NOT NULL,
  survival_time_seconds bigint NOT NULL CHECK (survival_time_seconds >= 0),
  statistics_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX smp_hardcore_deaths_recent_idx ON smp_hardcore_deaths(world_id, occurred_at DESC);

CREATE TABLE smp_arenas (
  arena_id uuid PRIMARY KEY,
  arena_key text NOT NULL UNIQUE,
  display_name text NOT NULL,
  world_id text NOT NULL REFERENCES smp_worlds(world_id) ON DELETE RESTRICT,
  game_type text NOT NULL,
  minimum_players integer NOT NULL CHECK (minimum_players >= 1),
  maximum_players integer NOT NULL CHECK (maximum_players >= minimum_players),
  spawn_points jsonb NOT NULL DEFAULT '[]'::jsonb,
  spectator_spawn jsonb NOT NULL DEFAULT '{}'::jsonb,
  bounds jsonb NOT NULL DEFAULT '{}'::jsonb,
  reset_policy text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX smp_arenas_world_type_idx ON smp_arenas(world_id, game_type) WHERE is_active;

CREATE TABLE smp_events (
  event_id uuid PRIMARY KEY,
  event_key text NOT NULL UNIQUE,
  world_id text NOT NULL REFERENCES smp_worlds(world_id) ON DELETE RESTRICT,
  arena_id uuid REFERENCES smp_arenas(arena_id) ON DELETE SET NULL,
  display_name text NOT NULL,
  event_type text NOT NULL,
  lifecycle_state text NOT NULL CHECK (lifecycle_state IN ('DRAFT','SCHEDULED','REGISTRATION_OPEN','CHECK_IN','STARTING','LIVE','FINISHED','ARCHIVED','CANCELLED')),
  starts_at timestamptz,
  ends_at timestamptz,
  registration_opens_at timestamptz,
  maximum_players integer NOT NULL CHECK (maximum_players >= 1),
  minimum_players integer NOT NULL CHECK (minimum_players >= 1 AND minimum_players <= maximum_players),
  waitlist_enabled boolean NOT NULL DEFAULT true,
  configuration jsonb NOT NULL DEFAULT '{}'::jsonb,
  rewards jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by_account_id uuid REFERENCES smp_minecraft_accounts(account_id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at)
);
CREATE INDEX smp_events_state_start_idx ON smp_events(lifecycle_state, starts_at);
CREATE INDEX smp_events_world_start_idx ON smp_events(world_id, starts_at DESC);

CREATE TABLE smp_event_registrations (
  event_registration_id uuid PRIMARY KEY,
  event_id uuid NOT NULL REFERENCES smp_events(event_id) ON DELETE CASCADE,
  account_id uuid NOT NULL REFERENCES smp_minecraft_accounts(account_id) ON DELETE CASCADE,
  guild_id uuid REFERENCES smp_guilds(guild_id) ON DELETE SET NULL,
  status text NOT NULL CHECK (status IN ('REGISTERED','WAITLISTED','CHECKED_IN','WITHDRAWN','DISQUALIFIED')),
  registered_at timestamptz NOT NULL DEFAULT now(),
  checked_in_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (event_id, account_id)
);
CREATE INDEX smp_event_registrations_event_status_idx ON smp_event_registrations(event_id, status, registered_at);

CREATE TABLE smp_event_results (
  event_result_id uuid PRIMARY KEY,
  event_id uuid NOT NULL REFERENCES smp_events(event_id) ON DELETE CASCADE,
  account_id uuid REFERENCES smp_minecraft_accounts(account_id) ON DELETE SET NULL,
  guild_id uuid REFERENCES smp_guilds(guild_id) ON DELETE SET NULL,
  placement integer CHECK (placement > 0),
  score numeric(20,6) NOT NULL DEFAULT 0,
  rewards jsonb NOT NULL DEFAULT '{}'::jsonb,
  result_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (account_id IS NOT NULL OR guild_id IS NOT NULL)
);
CREATE UNIQUE INDEX smp_event_results_account_uq ON smp_event_results(event_id, account_id) WHERE account_id IS NOT NULL;
CREATE UNIQUE INDEX smp_event_results_guild_uq ON smp_event_results(event_id, guild_id) WHERE guild_id IS NOT NULL;

CREATE TABLE smp_creative_submissions (
  creative_submission_id uuid PRIMARY KEY,
  world_id text NOT NULL REFERENCES smp_worlds(world_id) ON DELETE RESTRICT,
  account_id uuid NOT NULL REFERENCES smp_minecraft_accounts(account_id) ON DELETE RESTRICT,
  plot_reference text NOT NULL,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  image_references jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','UNDER_REVIEW','FEATURED','REJECTED','WITHDRAWN')),
  reviewer_account_id uuid REFERENCES smp_minecraft_accounts(account_id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  submitted_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX smp_creative_submissions_review_idx ON smp_creative_submissions(world_id, status, submitted_at);

CREATE TABLE smp_featured_builds (
  featured_build_id uuid PRIMARY KEY,
  creative_submission_id uuid NOT NULL UNIQUE REFERENCES smp_creative_submissions(creative_submission_id) ON DELETE CASCADE,
  world_id text NOT NULL REFERENCES smp_worlds(world_id) ON DELETE RESTRICT,
  feature_state text NOT NULL DEFAULT 'ACTIVE' CHECK (feature_state IN ('ACTIVE','RETIRED')),
  featured_by_account_id uuid REFERENCES smp_minecraft_accounts(account_id) ON DELETE SET NULL,
  featured_at timestamptz NOT NULL DEFAULT now(),
  retired_at timestamptz,
  website_reference text,
  CHECK (retired_at IS NULL OR retired_at >= featured_at)
);
CREATE INDEX smp_featured_builds_active_idx ON smp_featured_builds(world_id, featured_at DESC) WHERE feature_state = 'ACTIVE';

CREATE TABLE smp_world_resets (
  world_reset_id uuid PRIMARY KEY,
  world_id text NOT NULL REFERENCES smp_worlds(world_id) ON DELETE RESTRICT,
  reset_type text NOT NULL,
  state text NOT NULL CHECK (state IN ('SCHEDULED','WARNING_24H','WARNING_1H','WARNING_15M','WARNING_5M','WARNING_1M','LOCK_ENTRY','EVACUATING','SAVING','BACKING_UP','UNLOADING','REGENERATING','LOADING','VALIDATING','OPEN','COMPLETED','ABORTED','FAILED')),
  scheduled_for timestamptz NOT NULL,
  started_at timestamptz,
  completed_at timestamptz,
  initiated_by_account_id uuid REFERENCES smp_minecraft_accounts(account_id) ON DELETE SET NULL,
  backup_required boolean NOT NULL DEFAULT true,
  failure_reason text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at)
);
CREATE INDEX smp_world_resets_due_idx ON smp_world_resets(state, scheduled_for);
CREATE INDEX smp_world_resets_history_idx ON smp_world_resets(world_id, scheduled_for DESC);

CREATE TABLE smp_world_backups (
  world_backup_id uuid PRIMARY KEY,
  world_id text NOT NULL REFERENCES smp_worlds(world_id) ON DELETE RESTRICT,
  world_reset_id uuid REFERENCES smp_world_resets(world_reset_id) ON DELETE SET NULL,
  backup_kind text NOT NULL,
  storage_reference text NOT NULL,
  checksum_sha256 char(64),
  byte_size bigint CHECK (byte_size >= 0),
  state text NOT NULL CHECK (state IN ('PENDING','RUNNING','VERIFIED','FAILED','EXPIRED')),
  retention_until timestamptz,
  started_at timestamptz NOT NULL DEFAULT now(),
  verified_at timestamptz,
  failure_reason text,
  CHECK (verified_at IS NULL OR verified_at >= started_at)
);
CREATE INDEX smp_world_backups_world_state_idx ON smp_world_backups(world_id, state, started_at DESC);

CREATE TABLE smp_moderation_actions (
  moderation_action_id uuid PRIMARY KEY,
  target_account_id uuid NOT NULL REFERENCES smp_minecraft_accounts(account_id) ON DELETE RESTRICT,
  actor_account_id uuid REFERENCES smp_minecraft_accounts(account_id) ON DELETE SET NULL,
  action_type text NOT NULL CHECK (action_type IN ('WARN','MUTE','TEMP_MUTE','BAN','TEMP_BAN','KICK','FREEZE','UNFREEZE','NOTE')),
  reason text NOT NULL,
  world_id text REFERENCES smp_worlds(world_id) ON DELETE SET NULL,
  issued_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz,
  revoked_at timestamptz,
  revoked_by_account_id uuid REFERENCES smp_minecraft_accounts(account_id) ON DELETE SET NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CHECK (expires_at IS NULL OR expires_at > issued_at),
  CHECK (revoked_at IS NULL OR revoked_at >= issued_at)
);
CREATE INDEX smp_moderation_actions_target_idx ON smp_moderation_actions(target_account_id, issued_at DESC);

CREATE TABLE smp_account_links (
  account_link_id uuid PRIMARY KEY,
  account_id uuid NOT NULL REFERENCES smp_minecraft_accounts(account_id) ON DELETE CASCADE,
  platform_user_id uuid,
  code_hash char(64) NOT NULL UNIQUE CHECK (code_hash ~ '^[0-9a-f]{64}$'),
  state text NOT NULL DEFAULT 'ISSUED' CHECK (state IN ('ISSUED','CONSUMED','REVOKED','EXPIRED')),
  issued_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  revoked_at timestamptz,
  requested_ip_hash char(64),
  correlation_id uuid,
  CHECK (expires_at > issued_at),
  CHECK (consumed_at IS NULL OR consumed_at >= issued_at),
  CHECK (revoked_at IS NULL OR revoked_at >= issued_at)
);
CREATE INDEX smp_account_links_account_state_idx ON smp_account_links(account_id, state, expires_at DESC);
CREATE INDEX smp_account_links_platform_idx ON smp_account_links(platform_user_id) WHERE platform_user_id IS NOT NULL;

CREATE TABLE smp_notifications (
  notification_id uuid PRIMARY KEY,
  account_id uuid REFERENCES smp_minecraft_accounts(account_id) ON DELETE CASCADE,
  channel text NOT NULL CHECK (channel IN ('MINECRAFT','WEBSITE','DISCORD','SYSTEM')),
  notification_type text NOT NULL,
  payload jsonb NOT NULL,
  state text NOT NULL DEFAULT 'PENDING' CHECK (state IN ('PENDING','DELIVERED','FAILED','DISMISSED')),
  created_at timestamptz NOT NULL DEFAULT now(),
  delivered_at timestamptz,
  failure_reason text
);
CREATE INDEX smp_notifications_pending_idx ON smp_notifications(state, created_at) WHERE state = 'PENDING';
CREATE INDEX smp_notifications_account_idx ON smp_notifications(account_id, created_at DESC);

CREATE TABLE smp_integration_state (
  integration_key text PRIMARY KEY,
  enabled boolean NOT NULL DEFAULT true,
  health_state text NOT NULL CHECK (health_state IN ('UNKNOWN','HEALTHY','WARNING','ERROR','DISABLED')),
  last_success_at timestamptz,
  last_failure_at timestamptz,
  consecutive_failures integer NOT NULL DEFAULT 0 CHECK (consecutive_failures >= 0),
  last_error_redacted text,
  state_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE smp_audit_logs (
  audit_log_id uuid PRIMARY KEY,
  actor_account_id uuid REFERENCES smp_minecraft_accounts(account_id) ON DELETE SET NULL,
  action text NOT NULL,
  target_type text NOT NULL,
  target_id text,
  world_id text REFERENCES smp_worlds(world_id) ON DELETE SET NULL,
  before_state jsonb,
  after_state jsonb,
  reason text,
  correlation_id uuid NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX smp_audit_logs_target_idx ON smp_audit_logs(target_type, target_id, occurred_at DESC);
CREATE INDEX smp_audit_logs_actor_idx ON smp_audit_logs(actor_account_id, occurred_at DESC);
CREATE INDEX smp_audit_logs_correlation_idx ON smp_audit_logs(correlation_id);

CREATE TABLE smp_event_outbox (
  outbox_event_id uuid PRIMARY KEY,
  event_type text NOT NULL,
  aggregate_type text NOT NULL,
  aggregate_id text NOT NULL,
  world_id text REFERENCES smp_worlds(world_id) ON DELETE SET NULL,
  payload jsonb NOT NULL,
  idempotency_key text NOT NULL UNIQUE,
  correlation_id uuid NOT NULL,
  state text NOT NULL DEFAULT 'PENDING' CHECK (state IN ('PENDING','LEASED','DELIVERED','DEAD_LETTER')),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  next_attempt_at timestamptz NOT NULL DEFAULT now(),
  lease_expires_at timestamptz,
  delivered_at timestamptz,
  last_error_redacted text,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  CHECK (state <> 'DELIVERED' OR delivered_at IS NOT NULL)
);
CREATE INDEX smp_event_outbox_dispatch_idx ON smp_event_outbox(state, next_attempt_at) WHERE state IN ('PENDING','LEASED');
CREATE INDEX smp_event_outbox_aggregate_idx ON smp_event_outbox(aggregate_type, aggregate_id, occurred_at);

-- Exact initial World Registry records. Future registry synchronization updates revisioned data.
INSERT INTO smp_worlds (
  world_id, minecraft_world_name, display_name, public_type, module_type, season_label, status, description,
  size_label, difficulty_label, border_size, pvp_mode, guild_mode, points_enabled, currency_id, claims_enabled,
  economy_enabled, inventory_group, reset_policy, archive_policy, discord_enabled, website_visible, map_visible,
  maintenance_mode, access_permission, spawn_x, spawn_y, spawn_z
) VALUES
('ashfall','nx_ashfall','Ashfall','Survival','SURVIVAL','Season 7','LIVE','The flagship survival map. Nation borders, claim wars and a player-run economy on redstone freight lines.','24k x 24k','Hard',24000,'ENABLED','FULL',true,'NEXUS_POINTS',true,true,'ASHFALL_GROUP','{"mode":"SEASONAL"}','{"mode":"ARCHIVE_AT_SEASON_END","readOnlyAfterArchive":true}',true,true,true,false,'smpplatform.world.ashfall',0.5,80,0.5),
('obsidian-gate','nx_obsidian_gate','Obsidian Gate','Hardcore','HARDCORE','Season 7','LIVE','One life. Shared world. Death moves players to spectator until the Sunday-night reset window.','8k x 8k','Brutal',8000,'ENABLED','CONFIGURABLE',true,'HARDCORE_POINTS',false,false,'HARDCORE_GROUP','{"mode":"CONFIGURED_HARDCORE_WINDOW"}','{"mode":"SNAPSHOT_ON_SEASON_END","readOnlyAfterArchive":true}',true,true,true,false,'smpplatform.world.obsidian-gate',0.5,90,0.5),
('atrium','nx_atrium','The Atrium','Creative','CREATIVE','Permanent','LIVE','Plot-based creative sandbox with WorldEdit, custom palettes and monthly featured build showcases.','Plots 128x128','Peaceful',24000,'DISABLED','SOCIAL_OPTIONAL',true,'BUILD_POINTS',false,false,'CREATIVE_GROUP','{"mode":"PERMANENT"}','{"mode":"BACKUP_ONLY"}',true,true,true,false,'smpplatform.world.atrium',0.5,80,0.5),
('colosseum','nx_colosseum','Neon Colosseum','Events','EVENT','Rotating','LIVE','Arena network for Sky Duels, Block Rush and Friday-night 64-player Gauntlet tournaments.','Instanced','Normal',0,'EVENT_CONTROLLED','TEAM_COMPETITION',true,'EVENT_POINTS',false,false,'EVENT_GROUP','{"mode":"PER_EVENT_INSTANCE"}','{"mode":"RESULTS_AND_INSTANCE_BACKUP"}',true,true,false,false,'smpplatform.world.colosseum',0.5,80,0.5),
('quarry','nx_quarry','The Quarry','Resource','RESOURCE','Weekly reset','SEASONAL','Resource world that regenerates every Monday 04:00 UTC to protect the main map terrain.','12k x 12k','Normal',12000,'ENABLED','INHERIT_ASHFALL',true,'NEXUS_POINTS',false,true,'ASHFALL_GROUP','{"mode":"SCHEDULED_REGENERATE","timezone":"UTC","cron":"0 4 * * MON","backupRequired":true,"abortOnBackupFailure":true}','{"mode":"NONE"}',true,true,true,false,'smpplatform.world.quarry',0.5,80,0.5),
('verdance','nx_verdance','Verdance','Survival','ARCHIVE','Season 6','ARCHIVED','The Season 6 map, frozen and open for tours; members may obtain its world file through the portal.','20k x 20k','Hard',20000,'DISABLED','READ_ONLY_HISTORICAL',false,NULL,false,false,'ARCHIVE_GROUP','{"mode":"NEVER"}','{"mode":"TOUR_ONLY","readOnlyAfterArchive":true}',false,true,true,false,'smpplatform.world.verdance',0.5,80,0.5);

COMMIT;
